name: tu_app_de_archivos
description: Aplicaci칩n para compartir archivos de cualquier carrera o especialidad.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^2.30.0

  # Firebase Auth para autenticaci칩n
  firebase_auth: ^4.17.9

  # Cloud Firestore para base de datos en tiempo real
  cloud_firestore: ^4.15.8

  # Firebase Storage para archivos
  firebase_storage: ^11.7.7

  # Para cargar im치genes de red y locales
  cached_network_image: ^3.3.1

  # Manejo de fechas m치s amigable
  intl: ^0.19.0

  # Otras utilidades recomendadas
  provider: ^6.1.2

  # Manejo de archivos locales
  file_picker: ^8.0.3
  path_provider: ^2.1.3

  # Para manejo de streams y colecciones
  collection: ^1.18.0
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true